{{- define "app.secrets" -}}
  {{- printf "|" }}
array:
  {{- range .Values.secretProvider.secrets }}
  {{ printf "- |" | indent 2 }}
  {{ printf "objectName: %s" .objectName | indent 4 }}
  {{ printf "objectType: secret" | indent 4 }}
  {{ printf "objectAlias: %s" .objectAlias | indent 4 }}
  {{- end }}
{{- end -}}
{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Values.secretProvider.name }}
spec:
  provider: azure
  secretObjects:
  - secretName: splitproxy
    type: Opaque
    data:
    - objectName: SplitIoApiKey
      key: SplitIoApiKey
    - objectName: SplitIoProxyApiKey
      key: SplitIoProxyApiKey
    - objectName: SplitDashboardPassword
      key: SplitDashboardPassword
  parameters:
    keyvaultName: {{ $.Values.secretProvider.keyVaultName }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ $.Values.secretProvider.managedIdentity }}
    tenantId: {{ $.Values.secretProvider.tenantId }}
    objects: {{ include "app.secrets" $ | indent 6 }}
{{- end }}