apiVersion: v1
kind: Service
metadata:
  name: my-release
  namespace: default
  annotations:
    {{ include "pgcat.annotations" $ | indent 4 | trim }}
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{ include "pgcat.labels" $ | indent 4 | trim }}
    {{- with .tags }}
    {{- range $tag, $val := . }}
    {{ $tag }}: {{ $val | replace " " "-" | quote }}
    {{- end }}
    {{- end }}
    {{- with .labels }}
    {{- range $label, $lvalue := . }}
    {{ $label }}: {{ $lvalue | replace " " "-" | quote }}
    {{- end }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    
  selector:
    {{ include "pgcat.labels" $ | indent 4 | trim }}
    {{- with .tags }}
    {{- range $tag, $val := . }}
    {{ $tag }}: {{ $val | replace " " "-" | quote }}
    {{- end }}
    {{- end }}
    {{- with .labels }}
    {{- range $label, $lvalue := . }}
    {{ $label }}: {{ $lvalue | replace " " "-" | quote }}
    {{- end }}
    {{- end }}