apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redpanda-connect.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redpanda-connect.labels" . | nindent 4 }}
data:
  connect.yaml: |
    {{- with .Values.logger }}
    logger:
      {{- toYaml . | nindent 6}} 
    {{- end }}
    {{- with .Values.metrics }}
    metrics:
      {{- toYaml . | nindent 6}} 
    {{- end }}
    {{- with .Values.tracing }}
    tracer:
      {{- toYaml . | nindent 6}}
    {{- end }}
    {{- with .Values.http }}
    http:
      {{- toYaml . | nindent 6}}
    {{- end }}
    {{- if and .Values.config (ne .Values.streams.enabled true) }}
    {{- with .Values.config }}
    {{- toYaml . | nindent 4}}
    {{- end -}}

    {{- else if and .Values.streams.enabled .Values.streams.streamsConfigMap }}
    {{- else }}
    input:
      label: "no_config_in"
      generate:
        mapping: root = "This Redpanda-Connect instance is unconfigured!"
        interval: 1m
    output:
      label: "no_config_out"
      stdout:
        codec: lines
    {{- end -}}
