{{ if .Values.ctrl.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-ctrl
  labels:
    io.metrico.service: qryn-ctrl
  {{- include "qryn-all-in-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ctrl.type }}
  selector:
    io.metrico.service: qryn-ctrl
  {{- include "qryn-all-in-one.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.ctrl.port }}
      targetPort: {{ .Values.ctrl.port }}
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-ctrl
  labels:
    io.metrico.service: qryn-ctrl
  {{- include "qryn-all-in-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ctrl.replicas }}
  revisionHistoryLimit: {{ .Values.ctrl.revisionHistoryLimit }}
  selector:
    matchLabels:
      io.metrico.service: qryn-ctrl
    {{- include "qryn-all-in-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.metrico.service: qryn-ctrl
        sidecar.istio.io/inject: "false"
      {{- include "qryn-all-in-one.selectorLabels" . | nindent 8 }}
      {{- with .Values.ctrl.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      {{- if .Values.ctrl.additionalContainers }}
      {{- include "common.tplvalues.render" (dict "value" .Values.ctrl.additionalContainers "context" $) | trim | nindent 8 }}
      {{- end }}
        - command:
            - ./qryn-ctrl
            - -web
          env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - configMapRef:
                name: {{ include "qryn-all-in-one.fullname" . }}-qryn
          image: {{ .Values.ctrl.image.repository }}:{{ .Values.ctrl.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.ctrl.imagePullPolicy }}
          name: qryn-ctrl
          ports:
            - containerPort: {{ .Values.ctrl.port }}
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: qryn-dckr
      {{- with .Values.ctrl.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ctrl.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ctrl.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
