{{ if .Values.reader.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-reader
  labels:
    io.metrico.service: qryn-reader
  {{- include "qryn-all-in-one.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reader.type }}
  selector:
    io.metrico.service: qryn-reader
  {{- include "qryn-all-in-one.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{.Values.reader.env.qrynHttpSettingsPort }}
      targetPort: {{.Values.reader.env.qrynHttpSettingsPort }}
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-reader
  labels:
    io.metrico.service: qryn-reader
    {{- include "qryn-all-in-one.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.reader.replicas }}
  revisionHistoryLimit: {{ .Values.reader.revisionHistoryLimit }}
  selector:
    matchLabels:
      io.metrico.service: qryn-reader
      {{- include "qryn-all-in-one.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.metrico.service: qryn-reader
        {{- include "qryn-all-in-one.selectorLabels" . | nindent 8 }}
      {{- with .Values.reader.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.reader.initContainers.enabled }}
      initContainers:
      {{- if .Values.reader.initContainers.containers }}
      {{- include "common.tplvalues.render" (dict "value" .Values.reader.initContainers.containers "context" $) | trim | nindent 8 }}
      {{- end }}
      {{- end }} 
      containers:
        - env:
            - name: QRYN_HTTP_SETTINGS_PORT
              value: {{ quote .Values.reader.env.qrynHttpSettingsPort }}
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - configMapRef:
                name: {{ include "qryn-all-in-one.fullname" . }}-qryn
          image: {{ .Values.reader.image.repository }}:{{ .Values.reader.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.reader.imagePullPolicy }}
          name: qryn-reader
          ports:
            - name: http
              containerPort: {{.Values.reader.env.qrynHttpSettingsPort }}
              protocol: TCP
          resources: {{- toYaml .Values.reader.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ .Values.reader.livenessProbe.initialDelaySeconds | default 15 }}
            periodSeconds: {{ .Values.reader.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.reader.livenessProbe.timeoutSeconds | default 3 }}
            failureThreshold: {{ .Values.reader.livenessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.reader.livenessProbe.successThreshold | default 1 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ .Values.reader.readinessProbe.initialDelaySeconds | default 15 }}
            periodSeconds: {{ .Values.reader.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.reader.readinessProbe.timeoutSeconds | default 3 }}
            failureThreshold: {{ .Values.reader.readinessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.reader.readinessProbe.successThreshold | default 1 }}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qryn-dckr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- with .Values.reader.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reader.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reader.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.reader.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-reader
  labels:
    io.metrico.service: qryn-reader
    {{- include "qryn-all-in-one.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "qryn-all-in-one.fullname" . }}-reader
  minReplicas: {{ .Values.reader.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.reader.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.reader.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.reader.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.reader.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.reader.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{ end }}