{{- if .Values.writer.enabled -}}
{{- if .Values.writer.ingress.enabled -}}
{{- if and .Values.reader.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.reader.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.reader.ingress.annotations "kubernetes.io/ingress.class" .Values.reader.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "qryn-all-in-one.fullname" . }}-writer
  labels:
    {{- include "qryn-all-in-one.labels" . | nindent 4 }}
  {{- with .Values.writer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.writer.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.writer.ingress.className }}
  {{- end }}
  {{- if .Values.writer.ingress.tls }}
  tls:
    {{- range .Values.writer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{ $port := .Values.writer.env.qrynHttpSettingsPort }}
    {{- range .Values.writer.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "qryn-all-in-one.fullname" . }}-writer
                port:
                  number: {{ $port }}
    {{- end }}
{{- end }}
{{- end }}