apiVersion: v2
name: clickhouseproxy
description: A Helm Chart for chproxy deployment to enable caching/proxying clickhouse
type: application
icon: https://www.chproxy.org/_astro/logo-white.1121eedc.svg
version: 1.0.7

dependencies:
  - name: redis
    version: 18.12.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
