image:
  repository: ghcr.io/mycarrier-devops/offload-operator
  tag: "26.14.9a3ddf9"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

leaderElection:
  enabled: true

serviceAccount:
  create: true
  # Override the service account name; defaults to release fullname
  name: ""

nodeSelector: {}
tolerations: []
affinity: {}
