{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "harbor-webhook.labels" . | nindent 4 }}
  name: {{ include "harbor-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "harbor-webhook.selectorLabels" . | nindent 6 }}
  {{- if and .Values.minAvailable (not (hasKey .Values "maxUnavailable")) }}
  minAvailable: {{ .Values.minAvailable }}
  {{- else if .Values.maxUnavailable }}
  maxUnavailable: {{ .Values.maxUnavailable }}
  {{- end }}
  {{- if .Values.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.unhealthyPodEvictionPolicy }}
  {{- end }}
{{ end }}