apiVersion: v2
name: qryn-aio
description: A Helm chart for Kubernetes

type: application

version: 0.2.17

sources:
  - https://github.com/metrico/qryn-cloud-helm

maintainers:
  - name: Qryn community

appVersion: "0.2.0"
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
