{{- if .Values.jobservice.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "harbor.jobservice" . }}
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.core.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: jobservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "harbor.jobservice" . }}
  minReplicas: {{ .Values.jobservice.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.jobservice.autoscaling.maxReplicas | default 5 }}
  metrics:
    {{- if .Values.jobservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.jobservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.jobservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.jobservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
