apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.core" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.core.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: core
  {{- if or (.Values.commonAnnotations) (.Values.vaultAnnotations) }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.vaultAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.vaultAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  app.conf: |+
    appname = Harbor
    runmode = prod
    enablegzip = true
    {{- if .Values.core.sessionLifetime }}
    sessiongcmaxlifetime = {{ .Values.core.sessionLifetime }}
    {{- end }}

    [prod]
    httpport = {{ ternary .Values.core.containerPorts.https .Values.core.containerPorts.http .Values.internalTLS.enabled | quote }}
