{{- if (eq .Values.application.deploymentType "deployment")  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myc-generic.fullname" . }}
  labels:
    {{- include "myc-generic.labels" . | nindent 4 }}
spec:
  ports:
    {{- range .Values.service.ports }}
    - containerPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      port: {{ .port }}
    {{- end }}
  selector:
    {{- include "myc-generic.selectorLabels" . | nindent 4 }}
{{- end }}