{{- if .Values.hyperdx.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hdx-oss.fullname" . }}-app-ingress
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.hyperdx.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.hyperdx.ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.hyperdx.ingress.proxyConnectTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.hyperdx.ingress.proxySendTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.hyperdx.ingress.proxyReadTimeout | quote }}
spec:
  ingressClassName: nginx
  {{- if .Values.hyperdx.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.hyperdx.ingress.host | default "localhost" }}
    secretName: {{ .Values.hyperdx.ingress.tlsSecretName | default "hyperdx-tls" }}
  {{- end }}
  rules:
    - host: {{ .Values.hyperdx.ingress.host | default "localhost" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "hdx-oss.fullname" . }}-app
                port:
                  number: {{ .Values.hyperdx.appPort }}
{{- end }}