---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouseproxy.fullname" . }}
  labels:
    {{- include "clickhouseproxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.config | nindent 4 }}