---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "clickhouseproxy.serviceAccountName" . }}
    labels:
        {{- include "clickhouseproxy.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}