---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "clickhouseproxy.fullname" . }}
    labels:
    {{- include "clickhouseproxy.labels" . | nindent 4 }}
spec:
    ports:
      {{- range .Values.service.ports }}
      - port: {{ .port }}
        targetPort: {{ .targetPort }}
        protocol: TCP
        name: {{ .name }}
    {{- end }}
    selector:
    {{- include "clickhouseproxy.selectorLabels" . | nindent 4 }}
