---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    resourceNames:
      - {{ .Release.Name }}-server
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-server
  labels:
     {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-server
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-server
    namespace: {{ .Release.Namespace }}
