apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "harborwebhook.fullname" . }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "harborwebhook.fullname" . }}"
  {{- end }}
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: {{ include "harborwebhook.fullname" . }}.{{ .Release.Namespace }}.svc
    sideEffects: None
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    clientConfig:
      service:
        name: {{ include "harborwebhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/webhook-v1-pod"
    {{- if .Values.webhook.namespaceSelector }}
    namespaceSelector:
      {{- .Values.webhook.namespaceSelector | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.webhook.objectSelector }}
    objectSelector:
      {{- .Values.webhook.objectSelector | toYaml | nindent 6 }}
    {{- end }}
