{{- if (or ( and (.Values.application.autoscaling.enabled) (hasPrefix "prod" .Values.environment.name)) (.Values.global.forceAutoscaling))}}
{{- $namespace := include "helm.namespace" . }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  maxReplicas: {{ default "5" .Values.application.autoscaling.maxReplicas }}
  minReplicas: {{ default "2" .Values.application.autoscaling.minReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  scaleTargetRef:
    {{- if (ne .Values.application.deploymentType "rollout")  }}
    apiVersion: apps/v1
    {{- else if (eq .Values.application.deploymentType "rollout") }}
    apiVersion: argoproj.io/v1alpha1
    {{- end}}
    {{- if (eq .Values.application.deploymentType "deployment")  }}
    kind: Deployment
    {{- else if (eq .Values.application.deploymentType "statefulset") }}
    kind: StatefulSet
    {{- else if (eq .Values.application.deploymentType "rollout") }}
    kind: Rollout
    {{- end}}
    name: {{ include "helm.fullname" . }}
  {{- end -}}
