{{if .Values.secrets.mounted }}
{{- $fullName := include "helm.fullname" . }}
{{- $namespace := include "helm.namespace" . }}
{{- $envScaling := include "helm.envScaling" . -}}
{{- $env := .Values.global.environment.name -}}
{{- range .Values.secrets.mounted }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-{{ .name }}-{{ $env }}-es
  namespace: {{ $namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    {{ include "helm.labels.standard" $ | indent 4 | trim }}
spec:
  refreshInterval: 15m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: {{ $fullName }}-{{ .name }}-{{ $env }}
    creationPolicy: Owner

  data:
  - secretKey: {{ .mountedFileName }}
    remoteRef:
      key: {{ .vault.path }}
      property: {{ .vault.property }}
      conversionStrategy: Default	
      decodingStrategy: None
{{- end -}}
{{- end -}}