{{- if (eq .Values.application.deploymentType "statefulset")  }}
{{- if .Values.serviceAccount.create }}
{{- if .Values.serviceAccount.rules }}
{{- $namespace := include "helm.namespace" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $namespace }}
  name: {{ .Values.serviceAccount.name | default (include "helm.fullname" .) }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
rules:
{{ toYaml .Values.serviceAccount.rules | indent 2 }}

{{- end }}
{{- end }}
{{- end }}