{{- if (eq .Values.application.deploymentType "statefulset")  }}
{{- if .Values.serviceAccount.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name | default (include "helm.fullname" .) }}
  namespace: {{ .Values.environment.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "helm.fullname" .) }}
  namespace: {{ .Values.environment.name }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.name | default (include "helm.fullname" .) }}
  apiGroup: ''
{{- end }}
{{- end }}
