{{- $fullName := include "helm.fullname" $ }}
{{- $namespace := include "helm.namespace" $ }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    release: kube-prometheus-stack
    prometheus.io/scrape: "true"
    {{ include "helm.labels.standard" $ | indent 4 | trim }}
    {{ include "helm.labels.version" $ | indent 4 | trim }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $namespace }}
  selector:
    matchExpressions:
      {{ include "helm.selectorExpressions" $ | indent 6 | trim }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ default "30s" .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ default "10s" .Values.serviceMonitor.scrapeTimeout }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      scheme: {{ default "http" .Values.serviceMonitor.scheme }}
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

