{{- if .Values.serviceAccount.create | default true }}
{{- $namespace := include "helm.namespace" . }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name | default (include "helm.fullname" .) }}
  namespace: {{ $namespace }}
  labels:
    {{ include "helm.labels.standard" . | indent 4 | trim }}
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
{{- end }}
