{{- if not (.Values.vpa).disable }}
{{- if or .Values.deployment .Values.statefulset }}
{{- $namespace := include "helm.namespace" . }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: {{ if .Values.deployment }}Deployment{{ else if .Values.statefulset }}StatefulSet{{ end }}
    name: {{ include "helm.fullname" . }}
  updatePolicy:
    updateMode: {{ default "Initial" .Values.vpaMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ include "helm.fullname" . }}
      controlledValues: {{ dig "vpa" "controlledValues" "RequestsOnly" (.Values | merge (dict)) }}
      minAllowed:
        cpu: 0m
        memory: 0Mi
      maxAllowed:
        cpu: {{ dig "resources" "limits" "cpu" "1000m" (default .Values.deployment .Values.statefulset) }}
        memory: {{ dig "resources" "limits" "memory" "1Gi" (default .Values.deployment .Values.statefulset) }}
    - containerName: istio-proxy
      mode: "Off"
{{- end }}
{{- end }}
