{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues) $) }}
{{- if (and (dig "autoscaling" "enabled" false $appValues) (or (hasPrefix "prod" $.Values.environment.name) (dig "autoscaling" "forceAutoscaling" false $appValues))) }}
{{- $envScaling := include "helm.envScaling" $ }}
{{- $namespace := include "helm.namespace" $ }}
{{- $fullName := include "helm.fullname" $appContext }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{ include "helm.specs.hpa" $appContext | indent 2 | trim }}
{{- end -}}
{{- end }}
