{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues "ctx" $globalCtx) $) }}
{{- $globalForceAutoscaling := $globalCtx.defaults.forceAutoscaling }}
{{- if (or (dig "autoscaling" "enabled" false $appValues) $globalForceAutoscaling) }}
{{- $envScaling := include "helm.envScaling" $ }}
{{- $namespace := include "helm.namespace" $ }}
{{- $fullName := include "helm.fullname" $appContext }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{ include "helm.specs.hpa" $appContext | indent 2 | trim }}
{{- end -}}
{{- end }}
