{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- range .Values.extraObjects }}
---
{{ include "common.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}