{{- if hasKey .Values "jobs" }}
{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- $namespace := include "helm.namespace" . }}
{{- $appStack := .Values.global.appStack }}
{{- $env := .Values.environment.name -}}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  {{- $rootContext := (merge (dict "job" . "ctx" $globalCtx) $) }}
  name: {{ $namespace }}-{{ $appStack }}-{{ .name | default "job" }}
  namespace: {{ $namespace }}
  labels:
    {{ include "helm.labels.dependencies" $rootContext | indent 4 | trim }}
    {{ include "helm.labels.standard" $rootContext | indent 4 | trim }}
    {{ include "helm.labels.version" $rootContext | indent 4 | trim }}
    {{- if .labels }}
    {{ toYaml .labels | indent 4 | trim }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  {{- with .annotations }}
    {{ toYaml . | indent 4 | trim }}
  {{- end }}
spec:
  {{ include "helm.specs.job" $rootContext | indent 2 | trim }}
{{- end }}
{{- end }}
