{{- if hasKey .Values "jobs" }}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  {{/* Create a root context with default values */}}
  {{- $rootContext := $ -}}
  {{- $rootContext := fromJson (include "helm.default-context" $rootContext) -}}
  {{- $_ := set $rootContext "job" . -}}
  name: {{ .name }}
  namespace: {{ $rootContext.defaults.environmentName | default $.Release.Namespace }}
  labels:
    {{ include "helm.labels.dependencies" $rootContext | indent 4 | trim }}
    {{ include "helm.labels.standard" $rootContext | indent 4 | trim }}
    {{ include "helm.labels.version" $rootContext | indent 4 | trim }}
    {{- if .labels }}
    {{ toYaml .labels | indent 4 | trim }}
    {{- end }}
  annotations:
  {{- with .annotations }}
    {{ toYaml . | indent 4 | trim }}
  {{- end }}
spec:
  {{ include "helm.specs.job" $rootContext | indent 2 | trim }}
{{- end }}
{{- end }}
