{{if .Values.secrets.mounted }}
{{- $namespace := include "helm.namespace" . }}
{{- $envScaling := include "helm.envScaling" . -}}
{{- $env := .Values.environment.name -}}
{{- $globalAppStack := .Values.global.appStack -}}

{{- range $.Values.secrets.mounted }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $globalAppStack }}-{{ .name }}-{{ $env }}-es
  namespace: {{ $namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: {{ $globalAppStack }}-{{ .name }}
    app.kubernetes.io/instance: {{ $globalAppStack }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  refreshInterval: 15m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: {{ $globalAppStack }}-{{ .name }}-{{ $env }}
    creationPolicy: Owner

  data:
  - secretKey: {{ .mountedFileName }}
    remoteRef:
      key: {{ .vault.path }}
      property: {{ .vault.property }}
      conversionStrategy: Default	
      decodingStrategy: None
{{- end -}}
{{- end -}}