{{- if (eq .Values.environment.name "dev") }}
{{- $fullName := include "helm.fullname" . }}
{{- $namespace := include "helm.namespace" . }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $fullName }}-offload-generator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    files:
                      - path: Apps/dev-{{ .Values.global.appStack | lower }}/v2-offload.yaml
                    repoURL: https://github.com/MyCarrier-DevOps/GitOps-dev.git
                    revision: main
                - list:
                    elementsYaml: '{{`{{`}} .offloads | toJson {{`}}`}}'
          - list:
              elements:
                - Values:
                    global:
                      appStack: {{ .Values.global.appStack | lower }}
                      forceAutoscaling: false
                      gitbranch: {{ .Values.global.gitbranch }}
                      language: {{ .Values.global.language }}
                    environment:
                      name: "{{`{{`}} .name {{`}}`}}"
                      dependencyenv: dev
                      domainOverride:
                        enabled: {{ .Values.environment.domainOverride.enabled }}
                        domain: {{ .Values.environment.domainOverride.domain }}
                    applications: {{- with .Values.applications -}}
                    {{- . | toYaml | nindent 22 }}
                    {{- end }}
                    jobs: {{- with .Values.jobs }}
                    {{- . | toYaml | nindent 22 }}
                    {{- end }}
                    secrets: {{- with .Values.secrets }}
                    {{- . | toYaml | nindent 22 }}
                    {{- end }}
  template:
    metadata:
      name: "{{ $fullName }}-offload-{{`{{`}} .name {{`}}`}}"
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.deploy-reporter: ""
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ $namespace }}
      source:
        repoURL: https://github.com/MyCarrier-DevOps/ITM.Helm.Charts.git
        chart: mycarrier-helm
        targetRevision: {{ $.Chart.Version}}
        helm:
          values: |2+
            {{`{{`}}- $Values := .Values {{`}}`}}
            {{`{{`}}- .Values | toYaml | nindent 12 {{`}}`}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
          - Replace=true

        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 10m
{{- end -}}