{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues "ctx" $globalCtx) $) }}
{{- if (eq $appValues.deploymentType "rollout")  }}
{{- $fullName := include "helm.fullname" $appContext }}
{{- $namespace := include "helm.namespace" $ }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ $fullName }}{{- if contains "feature" $.Values.environment.name }}{{ end }}
  namespace: {{ $namespace }}
  labels:
    {{- include "helm.labels.dependencies" $appContext | indent 4 | trim }}
    {{ include "helm.labels.standard" $appContext | indent 4 | trim }}
    {{ include "helm.labels.version" $appContext | indent 4 | trim }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=true
spec:
  {{ include "helm.specs.rollout" $appContext | indent 2 | trim }}
---
{{- end }}
{{- end }}
