{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues "ctx" $globalCtx) $) }}
{{- $namespace := include "helm.namespace" $ }}
{{- $fullName := include "helm.fullname" $appContext }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=true
    {{- if and (hasKey $appValues "service") (hasKey $appValues.service "annotations") }}
    {{ toYaml $appValues.service.annotations | indent 4 | trim }}
    {{- end }}
  labels:
    {{ include "helm.labels.standard" $appContext | indent 4 | trim }}
spec:
  {{ include "helm.specs.service" $appContext | indent 2 | trim }}

{{- if (eq $appValues.deploymentType "rollout")  }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-preview
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- if and (hasKey $appValues "service") (hasKey $appValues.service "annotations") }}
    {{ toYaml $appValues.service.annotations | indent 4 | trim }}
    {{- end }}
  labels:
    {{ include "helm.labels.standard" $appContext | indent 4 | trim }}
spec:
  {{ include "helm.specs.service" $appContext | indent 2 | trim }}
{{- end }}

{{- if and (hasKey $appValues "service") (hasKey $appValues.service "aliases") }}
{{- range $appValues.service.aliases }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ . }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- if and (hasKey $appValues "service") (hasKey $appValues.service "annotations") }}
    {{ toYaml $appValues.service.annotations | indent 4 | trim }}
    {{- end }}
  labels:
    {{ include "helm.labels.standard" $appContext | indent 4 | trim }}
spec:
  type: {{ $appValues.service.type | default "ClusterIP" }}
  ports:
  {{- range $appValues.service.ports }}
    - name: {{ .name | lower }}
      port: {{ .port }}
      {{ if .targetPort }}targetPort: {{ .targetPort }}{{- end }}
  {{- end }}
  selector:
    {{ include "helm.labels.selector" $appContext | indent 4 | trim }}
  {{- if not $appValues.service.disableAffinity }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ default "600" $appValues.service.affinityTimeoutSeconds }}
  {{ end }}
{{- end }}
{{- end }}
{{- end }}
