{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues "ctx" $globalCtx) $) }}
{{- $fullName := include "helm.fullname" $appContext }}
{{- $namespace := include "helm.namespace" $ }}
{{- if dig "serviceMonitor" "enabled" false $appValues }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  {{- with $appValues.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    release: kube-prometheus-stack
    prometheus.io/scrape: "true"
    {{ include "helm.labels.standard" $appContext | indent 4 | trim }}
    {{ include "helm.labels.version" $appContext | indent 4 | trim }}
    {{- with $appValues.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{ include "helm.specs.servicemonitor" $appContext | indent 2 | trim }}
{{- end }}
{{- end }}

