{{- $v2migration := .Values.global.v2migration | default false -}}
{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues "ctx" $globalCtx) $) }}
{{- if (eq $appValues.deploymentType "statefulset")  }}
{{- $fullName := include "helm.fullname" $appContext }}
{{- $namespace := include "helm.namespace" $ }}
---
apiVersion: {{ $appValues.apiVersion | default "apps/v1" }}
kind: StatefulSet
metadata:
  name: {{ $fullName }}{{- if contains "feature" $.Values.environment.name }}{{ end }}
  namespace: {{ $namespace }}
  labels:
    {{ include "helm.labels.dependencies" $appContext | indent 4 | trim }}
    {{ include "helm.labels.standard" $appContext | indent 4 | trim }}
    {{ include "helm.labels.version" $appContext | indent 4 | trim }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    {{- if $v2migration }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Replace=true,Force=true
    {{- else }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=true
    {{- end }}
spec:
  {{ include "helm.specs.statefulset" $appContext | indent 2 | trim }}
---
{{- end -}}
{{- end }}