{{/* PERFORMANCE OPTIMIZATION: Precompute global context once instead of in every helper */}}
{{- $globalCtx := include "helm.context" $ | fromJson -}}
{{- range $appName, $appValues := .Values.applications }}
{{- $appContext := (merge (dict "appName" $appName "application" $appValues "ctx" $globalCtx) $) }}
{{- if and (hasKey $appValues "vpa") $appValues.vpa.enabled }}
{{- if or (eq $appValues.deploymentType "deployment") (eq $appValues.deploymentType "statefulset") }}
{{- $namespace := include "helm.namespace" $ }}
{{- $fullName := include "helm.fullname" $appContext }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{ include "helm.specs.vpa" $appContext | indent 2 | trim }}
{{- end }}
{{- end }}
{{- end }}
