name: 'Chart version bumper'
description: 'Bump a Helm chart & app version'
inputs:
  chart_name: 
    description: 'Name of the chart'
    required: true
  chart_version:
    description: 'The (new) version of the Helm chart'
    required: true
  app_version:
    description: 'The (new) appVersion'
    required: true
outputs:
  changeString:
    description: 'The changes summed up in a short message, meant for commits and PR titles'
  verboseChangeString:
    description: 'The changes summed up in a verbose way, meant for PR or Slack messages'
runs:
  using: 'node12'
  main: 'index.js'