{{- if eq (include "helm.alerts.enabled" .) "true" }}
{{- include "helm.alerts.validate" . }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: {{ include "helm.alerts.name" . }}-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: {{ .Values.global.appStack }}
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  name: {{ .Values.alerts.displayName }} Alerts
  interval: {{ .Values.alerts.interval }}
  folderUID: {{ .Values.alerts.folderUID }}
  instanceSelector:
    matchLabels:
      grafana-instance: grafana
  rules:
    {{- include "helm.alerts.rules" . | fromJsonArray | toYaml | nindent 4 }}
{{- end }}
